# zombie.worldMap.WorldMapSettings
package: zombie.worldMap
type: class
name: WorldMapSettings
extends: Object
modifiers:
  - public
  - final
fields:
  - name: VERSION
    modifiers:
      - public
      - static
    return:
      type: int
  - name: VERSION1
    modifiers:
      - public
      - static
    return:
      type: int
constructors:
  - name: WorldMapSettings
    modifiers:
      - public
methods:
  - name: getBoolean
    modifiers:
      - public
    return:
      type: boolean
  - name: getDouble
    modifiers:
      - public
    return:
      type: double
    parameters:
      - name: name
        type: String
  - name: getFileVersion
    modifiers:
      - public
    return:
      type: int
  - name: getInstance
    modifiers:
      - public
      - static
    return:
      type: WorldMapSettings
  - name: getOptionByIndex
    modifiers:
      - public
    return:
      type: ConfigOption
  - name: getOptionByName
    modifiers:
      - public
    return:
      type: ConfigOption
  - name: getOptionCount
    modifiers:
      - public
    return:
      type: int
  - name: load
    modifiers:
      - public
    return:
      type: void
  - name: Reset
    modifiers:
      - public
      - static
    return:
      type: void
  - name: save
    modifiers:
      - public
    return:
      type: void
  - name: setBoolean
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: name
        type: String
  - name: setDouble
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: name
        type: String
