# zombie.worldMap.WorldMapSettings
package: zombie.worldMap
type: class
name: WorldMapSettings
extends: Object
modifiers:
  - public
  - final
fields:
  - name: VERSION
    modifiers:
      - public
      - static
    returnType: int
  - name: VERSION1
    modifiers:
      - public
      - static
    returnType: int
constructors:
  - name: WorldMapSettings
    modifiers:
      - public
methods:
  - name: getBoolean
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: name
        type: String
  - name: getDouble
    modifiers:
      - public
    returnType: double
    parameters:
      - name: name
        type: String
      - name: defaultValue
        type: double
  - name: getFileVersion
    modifiers:
      - public
    returnType: int
  - name: getInstance
    modifiers:
      - public
      - static
    returnType: WorldMapSettings
  - name: getOptionByIndex
    modifiers:
      - public
    returnType: ConfigOption
    parameters:
      - name: index
        type: int
  - name: getOptionByName
    modifiers:
      - public
    returnType: ConfigOption
    parameters:
      - name: name
        type: String
  - name: getOptionCount
    modifiers:
      - public
    returnType: int
  - name: load
    modifiers:
      - public
    returnType: void
  - name: Reset
    modifiers:
      - public
      - static
    returnType: void
  - name: save
    modifiers:
      - public
    returnType: void
  - name: setBoolean
    modifiers:
      - public
    returnType: void
    parameters:
      - name: name
        type: String
      - name: value
        type: boolean
  - name: setDouble
    modifiers:
      - public
    returnType: void
    parameters:
      - name: name
        type: String
      - name: value
        type: double
