# zombie.scripting.objects.Recipe
package: zombie.scripting.objects
type: class
name: Recipe
extends: BaseScriptObject
modifiers:
  - public
fields:
  - name: AllowDestroyedItem
    modifiers:
      - public
    returnType: boolean
  - name: AllowFrozenItem
    modifiers:
      - public
    returnType: boolean
  - name: hidden
    modifiers:
      - public
    returnType: boolean
  - name: InSameInventory
    modifiers:
      - public
    returnType: boolean
  - name: LuaCreate
    modifiers:
      - public
    returnType: String
  - name: LuaGiveXP
    modifiers:
      - public
    returnType: String
  - name: LuaGrab
    modifiers:
      - public
    returnType: String
  - name: LuaTest
    modifiers:
      - public
    returnType: String
  - name: name
    modifiers:
      - public
    returnType: String
  - name: Result
    modifiers:
      - public
    returnType: Recipe.Result
  - name: skillRequired
    modifiers:
      - public
    returnType: ArrayList
  - name: Sound
    modifiers:
      - public
    returnType: String
  - name: Source
    modifiers:
      - public
      - final
    returnType: ArrayList
  - name: TimeToMake
    modifiers:
      - public
    returnType: float
constructors:
  - name: Recipe
    modifiers:
      - public
methods:
  - name: addRequiredSkill
    modifiers:
      - public
    returnType: void
    parameters:
      - name: perk
        type: PerkFactory.Perk
      - name: level
        type: int
  - name: clearRequiredSkills
    modifiers:
      - public
    returnType: void
  - name: DoResult
    modifiers:
      - public
    returnType: void
    parameters:
      - name: type
        type: String
  - name: DoSource
    modifiers:
      - public
    returnType: void
    parameters:
      - name: type
        type: String
  - name: FindIndexOf
    modifiers:
      - public
    returnType: int
    parameters:
      - name: a
        type: InventoryItem
  - name: findSource
    modifiers:
      - public
    returnType: Recipe.Source
    parameters:
      - name: sourceFullType
        type: String
  - name: getAnimNode
    modifiers:
      - public
    returnType: String
  - name: getCanPerform
    modifiers:
      - public
    returnType: String
  - name: getCategory
    modifiers:
      - public
    returnType: String
  - name: getFullType
    modifiers:
      - public
    returnType: String
  - name: getHeat
    modifiers:
      - public
    returnType: float
  - name: getLuaCreate
    modifiers:
      - public
    returnType: String
  - name: getLuaGiveXP
    modifiers:
      - public
    returnType: String
  - name: getLuaGrab
    modifiers:
      - public
    returnType: String
  - name: getLuaTest
    modifiers:
      - public
    returnType: String
  - name: getName
    modifiers:
      - public
    returnType: String
  - name: getNearItem
    modifiers:
      - public
    returnType: String
  - name: getNumberOfNeededItem
    modifiers:
      - public
    returnType: int
  - name: getOriginalname
    modifiers:
      - public
    returnType: String
  - name: getProp1
    modifiers:
      - public
    returnType: String
  - name: getProp2
    modifiers:
      - public
    returnType: String
  - name: getRequiredSkill
    modifiers:
      - public
    returnType: Recipe.RequiredSkill
    parameters:
      - name: index
        type: int
  - name: getRequiredSkillCount
    modifiers:
      - public
    returnType: int
  - name: getRequiredSkills
    modifiers:
      - public
    returnType: ArrayList
  - name: getResult
    modifiers:
      - public
    returnType: Recipe.Result
  - name: getSound
    modifiers:
      - public
    returnType: String
  - name: getSource
    modifiers:
      - public
    returnType: ArrayList
  - name: getTimeToMake
    modifiers:
      - public
    returnType: float
  - name: getTooltip
    modifiers:
      - public
    returnType: String
  - name: getWaterAmountNeeded
    modifiers:
      - public
    returnType: int
  - name: isAllowDestroyedItem
    modifiers:
      - public
    returnType: boolean
  - name: isAllowFrozenItem
    modifiers:
      - public
    returnType: boolean
  - name: isCanBeDoneFromFloor
    modifiers:
      - public
    returnType: boolean
  - name: isDestroy
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: sourceFullType
        type: String
  - name: isHidden
    modifiers:
      - public
    returnType: boolean
  - name: isKeep
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: sourceFullType
        type: String
  - name: isRemoveResultItem
    modifiers:
      - public
    returnType: boolean
  - name: isStopOnRun
    modifiers:
      - public
    returnType: boolean
  - name: isStopOnWalk
    modifiers:
      - public
    returnType: boolean
  - name: Load
    modifiers:
      - public
    returnType: void
    parameters:
      - name: name
        type: String
      - name: strArray
        type: String[]
  - name: needToBeLearn
    modifiers:
      - public
    returnType: boolean
  - name: noBrokenItems
    modifiers:
      - public
    returnType: boolean
  - name: setAllowDestroyedItem
    modifiers:
      - public
    returnType: void
    parameters:
      - name: allow
        type: boolean
  - name: setAllowFrozenItem
    modifiers:
      - public
    returnType: void
    parameters:
      - name: allow
        type: boolean
  - name: setAnimNode
    modifiers:
      - public
    returnType: void
    parameters:
      - name: animNode
        type: String
  - name: setCanBeDoneFromFloor
    modifiers:
      - public
    returnType: void
    parameters:
      - name: canBeDoneFromFloor
        type: boolean
  - name: setCanPerform
    modifiers:
      - public
    returnType: void
    parameters:
      - name: functionName
        type: String
  - name: setCategory
    modifiers:
      - public
    returnType: void
    parameters:
      - name: category
        type: String
  - name: setIsHidden
    modifiers:
      - public
    returnType: void
    parameters:
      - name: hide
        type: boolean
  - name: setLuaCreate
    modifiers:
      - public
    returnType: void
    parameters:
      - name: functionName
        type: String
  - name: setLuaGiveXP
    modifiers:
      - public
    returnType: void
    parameters:
      - name: functionName
        type: String
  - name: setLuaGrab
    modifiers:
      - public
    returnType: void
    parameters:
      - name: functionName
        type: String
  - name: setLuaTest
    modifiers:
      - public
    returnType: void
    parameters:
      - name: functionName
        type: String
  - name: setNearItem
    modifiers:
      - public
    returnType: void
    parameters:
      - name: nearItem
        type: String
  - name: setNeedToBeLearn
    modifiers:
      - public
    returnType: void
    parameters:
      - name: needToBeLearn
        type: boolean
  - name: setOriginalname
    modifiers:
      - public
    returnType: void
    parameters:
      - name: originalname
        type: String
  - name: setProp1
    modifiers:
      - public
    returnType: void
    parameters:
      - name: prop1
        type: String
  - name: setProp2
    modifiers:
      - public
    returnType: void
    parameters:
      - name: prop2
        type: String
  - name: setRemoveResultItem
    modifiers:
      - public
    returnType: void
    parameters:
      - name: removeResultItem
        type: boolean
  - name: setSound
    modifiers:
      - public
    returnType: void
    parameters:
      - name: sound
        type: String
  - name: setStopOnRun
    modifiers:
      - public
    returnType: void
    parameters:
      - name: stop
        type: boolean
  - name: setStopOnWalk
    modifiers:
      - public
    returnType: void
    parameters:
      - name: stop
        type: boolean
