# zombie.inventory.ClothingItemsDotTxt
package: zombie.inventory
type: class
name: ClothingItemsDotTxt
extends: Object
modifiers:
  - public
  - final
fields:
  - name: instance
    modifiers:
      - public
      - static
      - final
    returnType: ClothingItemsDotTxt
constructors:
  - name: ClothingItemsDotTxt
    modifiers:
      - public
methods:
  - name: LoadFile
    modifiers:
      - public
    returnType: void
