# zombie.inventory.CompressIdenticalItems
package: zombie.inventory
type: class
name: CompressIdenticalItems
extends: Object
modifiers:
  - public
  - final
constructors:
  - name: CompressIdenticalItems
    modifiers:
      - public
methods:
  - name: load
    modifiers:
      - public
      - static
    returnType: ArrayList
    parameters:
      - name: input
        type: ByteBuffer
      - name: WorldVersion
        type: " int"
      - name: Items
        type: " ArrayList"
        genericType: " ArrayList<InventoryItem>"
  - name: save
    modifiers:
      - public
      - static
    returnType: void
    parameters:
      - name: output
        type: ByteBuffer
  - name: save
    modifiers:
      - public
      - static
    returnType: ArrayList
    parameters:
      - name: output
        type: ByteBuffer
      - name: items
        type: " ArrayList"
        genericType: " ArrayList<InventoryItem>"
