# zombie.inventory.ItemPickerJava.ItemPickerRoom
package: zombie.inventory
type: class
name: ItemPickerJava.ItemPickerRoom
extends: Object
modifiers:
  - public
  - static
  - final
fields:
  - name: Containers
    modifiers:
      - public
    return:
      type: gnu.trove.map.hash.THashMap&lt;
      generic: gnu.trove.map.hash.THashMap<String,ItemPickerJava.ItemPickerContainer>
  - name: fillRand
    modifiers:
      - public
    return:
      type: int
  - name: isShop
    modifiers:
      - public
    return:
      type: boolean
  - name: specificId
    modifiers:
      - public
    return:
      type: String
constructors:
  - name: ItemPickerRoom
    modifiers:
      - public
