# zombie.inventory.ItemPickerJava.ItemPickerUpgradeWeapons
package: zombie.inventory
type: class
name: ItemPickerJava.ItemPickerUpgradeWeapons
extends: Object
modifiers:
  - public
  - static
  - final
fields:
  - name: name
    modifiers:
      - public
    return:
      type: String
  - name: Upgrades
    modifiers:
      - public
    return:
      type: ArrayList
      generic: ArrayList<String>
constructors:
  - name: ItemPickerUpgradeWeapons
    modifiers:
      - public
