# zombie.network.ServerSettings
package: zombie.network
type: class
name: ServerSettings
extends: Object
modifiers:
  - public
constructors:
  - name: ServerSettings
    modifiers:
      - public
methods:
  - name: addSpawnRegion
    modifiers:
      - public
    returnType: void
    parameters:
      - name: name
        type: String
  - name: clearSpawnRegions
    modifiers:
      - public
    returnType: void
  - name: deleteFiles
    modifiers:
      - public
    returnType: boolean
  - name: duplicateFiles
    modifiers:
      - public
    returnType: boolean
  - name: getErrorMsg
    modifiers:
      - public
    returnType: String
  - name: getName
    modifiers:
      - public
    returnType: String
  - name: getNumSpawnRegions
    modifiers:
      - public
    returnType: int
  - name: getSandboxOptions
    modifiers:
      - public
    returnType: SandboxOptions
  - name: getServerOptions
    modifiers:
      - public
    returnType: ServerOptions
  - name: getSpawnRegionFile
    modifiers:
      - public
    returnType: String
  - name: getSpawnRegionName
    modifiers:
      - public
    returnType: String
  - name: isValid
    modifiers:
      - public
    returnType: boolean
  - name: loadFiles
    modifiers:
      - public
    returnType: boolean
  - name: loadSpawnPointsFile
    modifiers:
      - public
    returnType: se.krka.kahlua.vm.KahluaTable
  - name: removeSpawnRegion
    modifiers:
      - public
    returnType: void
  - name: rename
    modifiers:
      - public
    returnType: boolean
  - name: resetToDefault
    modifiers:
      - public
    returnType: void
  - name: saveFiles
    modifiers:
      - public
    returnType: boolean
  - name: saveSpawnPointsFile
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: file
        type: String
