# zombie.network.ServerSettingsManager
package: zombie.network
type: class
name: ServerSettingsManager
extends: Object
modifiers:
  - public
fields:
  - name: instance
    modifiers:
      - public
      - static
      - final
    return:
      type: ServerSettingsManager
constructors:
  - name: ServerSettingsManager
    modifiers:
      - public
methods:
  - name: getNameInSettingsFolder
    modifiers:
      - public
    return:
      type: String
    parameters:
      - name: name
        type: String
  - name: getSettingsByIndex
    modifiers:
      - public
    return:
      type: ServerSettings
    parameters:
      - name: index
        type: int
  - name: getSettingsCount
    modifiers:
      - public
    return:
      type: int
  - name: getSettingsFolder
    modifiers:
      - public
    return:
      type: String
  - name: getSuffixes
    modifiers:
      - public
    return:
      type: ArrayList
      generic: ArrayList<String>
  - name: isValidName
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: name
        type: String
  - name: isValidNewName
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: newName
        type: String
  - name: readAllSettings
    modifiers:
      - public
    return:
      type: void
