# zombie.network.ServerSettingsManager
package: zombie.network
type: class
name: ServerSettingsManager
extends: Object
modifiers:
  - public
fields:
  - name: instance
    modifiers:
      - public
      - static
      - final
    returnType: ServerSettingsManager
constructors:
  - name: ServerSettingsManager
    modifiers:
      - public
methods:
  - name: getNameInSettingsFolder
    modifiers:
      - public
    returnType: String
  - name: getSettingsByIndex
    modifiers:
      - public
    returnType: ServerSettings
  - name: getSettingsCount
    modifiers:
      - public
    returnType: int
  - name: getSettingsFolder
    modifiers:
      - public
    returnType: String
  - name: getSuffixes
    modifiers:
      - public
    returnType: ArrayList
  - name: isValidName
    modifiers:
      - public
    returnType: boolean
  - name: isValidNewName
    modifiers:
      - public
    returnType: boolean
  - name: readAllSettings
    modifiers:
      - public
    returnType: void
