# zombie.network.ServerSettings
package: zombie.network
type: class
name: ServerSettings
extends: Object
modifiers:
  - public
constructors:
  - name: ServerSettings
    modifiers:
      - public
    parameters:
      - name: name
        type: String
methods:
  - name: addSpawnRegion
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: name
        type: String
      - name: file
        type: String
  - name: clearSpawnRegions
    modifiers:
      - public
    return:
      type: void
  - name: deleteFiles
    modifiers:
      - public
    return:
      type: boolean
  - name: duplicateFiles
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: newName
        type: String
  - name: getErrorMsg
    modifiers:
      - public
    return:
      type: String
  - name: getName
    modifiers:
      - public
    return:
      type: String
  - name: getNumSpawnRegions
    modifiers:
      - public
    return:
      type: int
  - name: getSandboxOptions
    modifiers:
      - public
    return:
      type: SandboxOptions
  - name: getServerOptions
    modifiers:
      - public
    return:
      type: ServerOptions
  - name: getSpawnRegionFile
    modifiers:
      - public
    return:
      type: String
    parameters:
      - name: index
        type: int
  - name: getSpawnRegionName
    modifiers:
      - public
    return:
      type: String
    parameters:
      - name: index
        type: int
  - name: isValid
    modifiers:
      - public
    return:
      type: boolean
  - name: loadFiles
    modifiers:
      - public
    return:
      type: boolean
  - name: loadSpawnPointsFile
    modifiers:
      - public
    return:
      type: se.krka.kahlua.vm.KahluaTable
    parameters:
      - name: file
        type: String
  - name: removeSpawnRegion
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: index
        type: int
  - name: rename
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: newName
        type: String
  - name: resetToDefault
    modifiers:
      - public
    return:
      type: void
  - name: saveFiles
    modifiers:
      - public
    return:
      type: boolean
  - name: saveSpawnPointsFile
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: file
        type: String
      - name: professionsTable
        type: se.krka.kahlua.vm.KahluaTable
