# zombie.core.PerformanceSettings
package: zombie.core
type: class
name: PerformanceSettings
extends: Object
modifiers:
  - public
  - final
fields:
  - name: AnimationSkip
    modifiers:
      - public
      - static
    return:
      type: int
  - name: auto3DZombies
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: BaseStaticAnimFramerate
    modifiers:
      - public
      - static
    return:
      type: int
  - name: FogQuality
    modifiers:
      - public
      - static
    return:
      type: int
  - name: instance
    modifiers:
      - public
      - static
      - final
    return:
      type: PerformanceSettings
  - name: InterpolateAnims
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: LightingFPS
    modifiers:
      - public
      - static
    return:
      type: int
  - name: LightingFrameSkip
    modifiers:
      - public
      - static
    return:
      type: int
  - name: LightingThread
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: ManualFrameSkips
    modifiers:
      - public
      - static
    return:
      type: int
  - name: ModelLighting
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: NewRoofHiding
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: numberZombiesBlended
    modifiers:
      - public
      - static
    return:
      type: int
  - name: PuddlesQuality
    modifiers:
      - public
      - static
    return:
      type: int
  - name: UseFBOs
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: WaterQuality
    modifiers:
      - public
      - static
    return:
      type: int
  - name: ZombieAnimationSpeedFalloffCount
    modifiers:
      - public
      - static
    return:
      type: int
  - name: ZombieBonusFullspeedFalloff
    modifiers:
      - public
      - static
    return:
      type: int
constructors:
  - name: PerformanceSettings
    modifiers:
      - public
methods:
  - name: getFogQuality
    modifiers:
      - public
    return:
      type: int
  - name: getFramerate
    modifiers:
      - public
    return:
      type: int
  - name: getLightingFPS
    modifiers:
      - public
    return:
      type: int
  - name: getLightingQuality
    modifiers:
      - public
    return:
      type: int
  - name: getLockFPS
    modifiers:
      - public
      - static
    return:
      type: int
  - name: getNewRoofHiding
    modifiers:
      - public
    return:
      type: boolean
  - name: getPuddlesQuality
    modifiers:
      - public
    return:
      type: int
  - name: getUIRenderFPS
    modifiers:
      - public
    return:
      type: int
  - name: getWaterQuality
    modifiers:
      - public
    return:
      type: int
  - name: isFramerateUncapped
    modifiers:
      - public
    return:
      type: boolean
  - name: isUncappedFPS
    modifiers:
      - public
      - static
    return:
      type: boolean
  - name: setFogQuality
    modifiers:
      - public
    return:
      type: void
  - name: setFramerate
    modifiers:
      - public
    return:
      type: void
  - name: setFramerateUncapped
    modifiers:
      - public
    return:
      type: void
  - name: setLightingFPS
    modifiers:
      - public
    return:
      type: void
  - name: setLightingQuality
    modifiers:
      - public
    return:
      type: void
  - name: setLockFPS
    modifiers:
      - public
      - static
    return:
      type: void
  - name: setNewRoofHiding
    modifiers:
      - public
    return:
      type: void
  - name: setPuddlesQuality
    modifiers:
      - public
    return:
      type: void
  - name: setUncappedFPS
    modifiers:
      - public
      - static
    return:
      type: void
  - name: setWaterQuality
    modifiers:
      - public
    return:
      type: void
