# zombie.iso.sprite.shapers.FloorShaperDeDiamond.Settings
package: zombie.iso.sprite.shapers
type: class
name: FloorShaperDeDiamond.Settings
extends: SpritePaddingSettings.GenericZoomBasedSettingGroup
modifiers:
  - public
  - static
fields:
  - name: NotZoomed
    modifiers:
      - public
    returnType: FloorShaperDeDiamond.Settings.BorderSetting
  - name: ZoomedIn
    modifiers:
      - public
    returnType: FloorShaperDeDiamond.Settings.BorderSetting
  - name: ZoomedOut
    modifiers:
      - public
    returnType: FloorShaperDeDiamond.Settings.BorderSetting
constructors:
  - name: Settings
    modifiers:
      - public
methods:
  - name: getCurrentZoomSetting
    modifiers:
      - public
    returnType: FloorShaperDeDiamond.Settings.BorderSetting
