# zombie.iso.sprite.shapers.FloorShaperAttachedSprites.Settings.ASBorderSetting
package: zombie.iso.sprite.shapers
type: class
name: FloorShaperAttachedSprites.Settings.ASBorderSetting
extends: Object
modifiers:
  - public
  - static
fields:
  - name: borderThicknessDown
    modifiers:
      - public
    return:
      type: float
  - name: borderThicknessLR
    modifiers:
      - public
    return:
      type: float
  - name: borderThicknessUp
    modifiers:
      - public
    return:
      type: float
  - name: uvFraction
    modifiers:
      - public
    return:
      type: float
constructors:
  - name: ASBorderSetting
    modifiers:
      - public
  - name: ASBorderSetting
    modifiers:
      - public
    parameters:
      - name: borderThicknessUp
        type: float
      - name: borderThicknessDown
        type: float
      - name: borderThicknessLR
        type: float
      - name: uvFraction
        type: float
