# zombie.iso.sprite.shapers.FloorShaperDeDiamond.Settings.BorderSetting
package: zombie.iso.sprite.shapers
type: class
name: FloorShaperDeDiamond.Settings.BorderSetting
extends: Object
modifiers:
  - public
  - static
fields:
  - name: borderThicknessDown
    modifiers:
      - public
    returnType: float
  - name: borderThicknessLR
    modifiers:
      - public
    returnType: float
  - name: borderThicknessUp
    modifiers:
      - public
    returnType: float
  - name: uvFraction
    modifiers:
      - public
    returnType: float
constructors:
  - name: BorderSetting
    modifiers:
      - public
  - name: BorderSetting
    modifiers:
      - public
    parameters:
      - name: borderThicknessUp
        type: float
      - name: borderThicknessDown
        type: " float"
      - name: borderThicknessLR
        type: " float"
