# zombie.iso.sprite.shapers.FloorShaperAttachedSprites.Settings
package: zombie.iso.sprite.shapers
type: class
name: FloorShaperAttachedSprites.Settings
extends: SpritePaddingSettings.GenericZoomBasedSettingGroup
modifiers:
  - public
  - static
fields:
  - name: NotZoomed
    modifiers:
      - public
    returnType: FloorShaperAttachedSprites.Settings.ASBorderSetting
  - name: ZoomedIn
    modifiers:
      - public
    returnType: FloorShaperAttachedSprites.Settings.ASBorderSetting
  - name: ZoomedOut
    modifiers:
      - public
    returnType: FloorShaperAttachedSprites.Settings.ASBorderSetting
constructors:
  - name: Settings
    modifiers:
      - public
methods:
  - name: getCurrentZoomSetting
    modifiers:
      - public
    returnType: FloorShaperAttachedSprites.Settings.ASBorderSetting
