# zombie.iso.sprite.shapers.SpritePaddingSettings.Settings
package: zombie.iso.sprite.shapers
type: class
name: SpritePaddingSettings.Settings
extends: Object
modifiers:
  - public
  - static
fields:
  - name: AttachedSprites
    modifiers:
      - public
    returnType: FloorShaperAttachedSprites.Settings
  - name: FloorDeDiamond
    modifiers:
      - public
    returnType: FloorShaperDeDiamond.Settings
  - name: IsoPadding
    modifiers:
      - public
    returnType: SpritePadding.IsoPaddingSettings
constructors:
  - name: Settings
    modifiers:
      - public
