# zombie.iso.sprite.shapers.SpritePaddingSettings
package: zombie.iso.sprite.shapers
type: class
name: SpritePaddingSettings
extends: Object
modifiers:
  - public
constructors:
  - name: SpritePaddingSettings
    modifiers:
      - public
methods:
  - name: getSettings
    modifiers:
      - public
      - static
    return:
      type: SpritePaddingSettings.Settings
  - name: settingsFileChanged
    modifiers:
      - public
      - static
    return:
      type: void
