# zombie.iso.sprite.shapers.SpritePaddingSettings.GenericZoomBasedSettingGroup
package: zombie.iso.sprite.shapers
type: class
name: SpritePaddingSettings.GenericZoomBasedSettingGroup
extends: Object
modifiers:
  - public
  - abstract
  - static
constructors:
  - name: GenericZoomBasedSettingGroup
    modifiers:
      - public
methods:
  - name: getCurrentZoomSetting
    modifiers:
      - public
      - abstract
    return:
      type: ZoomBasedSetting
  - name: getCurrentZoomSetting
    modifiers:
      - public
      - static
    return:
      type: ZoomBasedSetting
    parameters:
      - name: zoomedIn
        type: ZoomBasedSetting
      - name: notZoomed
        type: ZoomBasedSetting
      - name: zoomedOut
        type: ZoomBasedSetting
