# zombie.iso.sprite.shapers.SpritePadding.IsoPaddingSettings
package: zombie.iso.sprite.shapers
type: class
name: SpritePadding.IsoPaddingSettings
extends: SpritePaddingSettings.GenericZoomBasedSettingGroup
modifiers:
  - public
  - static
fields:
  - name: NotZoomed
    modifiers:
      - public
    returnType: SpritePadding.IsoPaddingSettings.IsoBorderSetting
  - name: ZoomedIn
    modifiers:
      - public
    returnType: SpritePadding.IsoPaddingSettings.IsoBorderSetting
  - name: ZoomedOut
    modifiers:
      - public
    returnType: SpritePadding.IsoPaddingSettings.IsoBorderSetting
constructors:
  - name: IsoPaddingSettings
    modifiers:
      - public
methods:
  - name: getCurrentZoomSetting
    modifiers:
      - public
    returnType: SpritePadding.IsoPaddingSettings.IsoBorderSetting
