# zombie.iso.sprite.shapers.SpritePadding.IsoPaddingSettings.IsoBorderSetting
package: zombie.iso.sprite.shapers
type: class
name: SpritePadding.IsoPaddingSettings.IsoBorderSetting
extends: Object
modifiers:
  - public
  - static
fields:
  - name: borderThickness
    modifiers:
      - public
    return:
      type: float
  - name: uvFraction
    modifiers:
      - public
    return:
      type: float
constructors:
  - name: IsoBorderSetting
    modifiers:
      - public
  - name: IsoBorderSetting
    modifiers:
      - public
    parameters:
      - name: borderThickness
        type: float
