# zombie.iso.sprite.shapers.SpritePaddingSettings.Settings
package: zombie.iso.sprite.shapers
type: class
name: SpritePaddingSettings.Settings
extends: Object
modifiers:
  - public
  - static
fields:
  - name: AttachedSprites
    modifiers:
      - public
    return:
      type: FloorShaperAttachedSprites.Settings
  - name: FloorDeDiamond
    modifiers:
      - public
    return:
      type: FloorShaperDeDiamond.Settings
  - name: IsoPadding
    modifiers:
      - public
    return:
      type: SpritePadding.IsoPaddingSettings
constructors:
  - name: Settings
    modifiers:
      - public
