# zombie.meta.Meta
package: zombie.meta
type: class
name: Meta
extends: Object
modifiers:
  - public
  - final
notes: Created by LEMMYPC on 08/01/14.
fields:
  - name: instance
    modifiers:
      - public
      - static
      - final
    return:
      type: Meta
constructors:
  - name: Meta
    modifiers:
      - public
methods:
  - name: dealWithSquareSeen
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: square
        type: IsoGridSquare
  - name: dealWithSquareSeenActual
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: square
        type: IsoGridSquare
  - name: update
    modifiers:
      - public
    return:
      type: void
