# zombie.core.opengl.RenderSettings
package: zombie.core.opengl
type: class
name: RenderSettings
extends: Object
modifiers:
  - public
  - final
notes: TurboTuTone.
constructors:
  - name: RenderSettings
    modifiers:
      - public
methods:
  - name: applyRenderSettings
    modifiers:
      - public
    returnType: void
  - name: getAmbientForPlayer
    modifiers:
      - public
    returnType: float
  - name: getInstance
    modifiers:
      - public
      - static
    returnType: RenderSettings
  - name: getMaskClearColorForPlayer
    modifiers:
      - public
    returnType: Color
  - name: getPlayerSettings
    modifiers:
      - public
    returnType: RenderSettings.PlayerRenderSettings
  - name: legacyPostRender
    modifiers:
      - public
    returnType: void
  - name: update
    modifiers:
      - public
    returnType: void
