# zombie.core.opengl.RenderSettings.PlayerRenderSettings
package: zombie.core.opengl
type: class
name: RenderSettings.PlayerRenderSettings
extends: Object
modifiers:
  - public
  - static
fields:
  - name: CM_Ambient
    modifiers:
      - public
    return:
      type: float
  - name: CM_DayLightStrength
    modifiers:
      - public
    return:
      type: float
  - name: CM_Desaturation
    modifiers:
      - public
    return:
      type: float
  - name: CM_FogIntensity
    modifiers:
      - public
    return:
      type: float
  - name: CM_GlobalLight
    modifiers:
      - public
    return:
      type: ClimateColorInfo
  - name: CM_GlobalLightIntensity
    modifiers:
      - public
    return:
      type: float
  - name: CM_NightStrength
    modifiers:
      - public
    return:
      type: float
  - name: CM_ViewDistance
    modifiers:
      - public
    return:
      type: float
constructors:
  - name: PlayerRenderSettings
    modifiers:
      - public
methods:
  - name: getAmbient
    modifiers:
      - public
    return:
      type: float
  - name: getBlendColor
    modifiers:
      - public
    return:
      type: Color
  - name: getBlendIntensity
    modifiers:
      - public
    return:
      type: float
  - name: getBmod
    modifiers:
      - public
    return:
      type: float
  - name: getDarkness
    modifiers:
      - public
    return:
      type: float
  - name: getDesaturation
    modifiers:
      - public
    return:
      type: float
  - name: getFogMod
    modifiers:
      - public
    return:
      type: float
  - name: getGmod
    modifiers:
      - public
    return:
      type: float
  - name: getMaskClearColor
    modifiers:
      - public
    return:
      type: Color
  - name: getNight
    modifiers:
      - public
    return:
      type: float
  - name: getRmod
    modifiers:
      - public
    return:
      type: float
  - name: getSM_Alpha
    modifiers:
      - public
    return:
      type: float
  - name: getSM_Radius
    modifiers:
      - public
    return:
      type: float
  - name: getViewDistance
    modifiers:
      - public
    return:
      type: float
  - name: isApplyNightVisionGoggles
    modifiers:
      - public
    return:
      type: boolean
  - name: isExterior
    modifiers:
      - public
    return:
      type: boolean
