# zombie.core.opengl.RenderSettings
package: zombie.core.opengl
type: class
name: RenderSettings
extends: Object
modifiers:
  - public
  - final
notes: TurboTuTone.
constructors:
  - name: RenderSettings
    modifiers:
      - public
methods:
  - name: applyRenderSettings
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: playerIndex
        type: int
  - name: getAmbientForPlayer
    modifiers:
      - public
    return:
      type: float
    parameters:
      - name: plrIndex
        type: int
  - name: getInstance
    modifiers:
      - public
      - static
    return:
      type: RenderSettings
  - name: getMaskClearColorForPlayer
    modifiers:
      - public
    return:
      type: Color
    parameters:
      - name: plrIndex
        type: int
  - name: getPlayerSettings
    modifiers:
      - public
    return:
      type: RenderSettings.PlayerRenderSettings
    parameters:
      - name: playerIndex
        type: int
  - name: legacyPostRender
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: playerIndex
        type: int
  - name: update
    modifiers:
      - public
    return:
      type: void
