# zombie.erosion.ErosionConfig.Seeds
package: zombie.erosion
type: class
name: ErosionConfig.Seeds
extends: Object
modifiers:
  - public
  - static
  - final
constructors:
  - name: Seeds
    modifiers:
      - public
