# zombie.erosion.ErosionConfig.Debug
package: zombie.erosion
type: class
name: ErosionConfig.Debug
extends: Object
modifiers:
  - public
  - static
  - final
constructors:
  - name: Debug
    modifiers:
      - public
methods:
  - name: getEnabled
    modifiers:
      - public
    returnType: boolean
  - name: getStartDay
    modifiers:
      - public
    returnType: int
  - name: getStartMonth
    modifiers:
      - public
    returnType: int
