# zombie.erosion.ErosionConfig
package: zombie.erosion
type: class
name: ErosionConfig
extends: Object
modifiers:
  - public
  - final
fields:
  - name: debug
    modifiers:
      - public
      - final
    returnType: ErosionConfig.Debug
  - name: season
    modifiers:
      - public
      - final
    returnType: ErosionConfig.Season
  - name: seeds
    modifiers:
      - public
      - final
    returnType: ErosionConfig.Seeds
  - name: time
    modifiers:
      - public
      - final
    returnType: ErosionConfig.Time
constructors:
  - name: ErosionConfig
    modifiers:
      - public
methods:
  - name: consolePrint
    modifiers:
      - public
    returnType: void
  - name: getDebug
    modifiers:
      - public
    returnType: ErosionConfig.Debug
  - name: load
    modifiers:
      - public
    returnType: void
    parameters:
      - name: bb
        type: ByteBuffer
  - name: readFile
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: _file
        type: String
  - name: save
    modifiers:
      - public
    returnType: void
    parameters:
      - name: bb
        type: ByteBuffer
  - name: writeFile
    modifiers:
      - public
    returnType: void
    parameters:
      - name: _file
        type: String
