# zombie.erosion.ErosionConfig.Time
package: zombie.erosion
type: class
name: ErosionConfig.Time
extends: Object
modifiers:
  - public
  - static
  - final
constructors:
  - name: Time
    modifiers:
      - public
