# zombie.erosion.ErosionConfig.Season
package: zombie.erosion
type: class
name: ErosionConfig.Season
extends: Object
modifiers:
  - public
  - static
  - final
constructors:
  - name: Season
    modifiers:
      - public
