# zombie.chat.ChatSettings.FontSize
package: zombie.chat
type: enum
name: ChatSettings.FontSize
extends: Enum
modifiers:
  - public
  - static
fields:
  - name: Large
    modifiers:
      - public
      - static
      - final
    return:
      type: ChatSettings.FontSize
  - name: Medium
    modifiers:
      - public
      - static
      - final
    return:
      type: ChatSettings.FontSize
  - name: NotDefine
    modifiers:
      - public
      - static
      - final
    return:
      type: ChatSettings.FontSize
  - name: Small
    modifiers:
      - public
      - static
      - final
    return:
      type: ChatSettings.FontSize
methods:
  - name: __valueOf
    modifiers:
      - public
      - static
    return:
      type: ChatSettings.FontSize
      notes: the enum constant with the specified name
    notes: |-
      Returns the enum constant of this class with the specified name.
      The string must match
  - name: values
    modifiers:
      - public
      - static
    return:
      type: ChatSettings.FontSize
      generic: ChatSettings.FontSize[]
      notes: an array containing the constants of this enum class, in the order they
        are declared
    notes: |-
      Returns an array containing the constants of this enum class, in
      the order they are declared.
