# zombie.chat.ChatSettings
package: zombie.chat
type: class
name: ChatSettings
extends: Object
modifiers:
  - public
fields:
  - name: infinityRange
    modifiers:
      - public
      - static
      - final
    return:
      type: float
constructors:
  - name: ChatSettings
    modifiers:
      - public
  - name: ChatSettings
    modifiers:
      - public
    parameters:
      - name: bb
        type: ByteBuffer
methods:
  - name: getFont
    modifiers:
      - public
    return:
      type: UIFont
  - name: getFontColor
    modifiers:
      - public
    return:
      type: Color
  - name: getFontSize
    modifiers:
      - public
    return:
      type: String
  - name: getRange
    modifiers:
      - public
    return:
      type: float
  - name: getZombieAttractionRange
    modifiers:
      - public
    return:
      type: float
  - name: isAllowBBcode
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowChatIcons
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowColors
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowFonts
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowImages
    modifiers:
      - public
    return:
      type: boolean
  - name: isBold
    modifiers:
      - public
    return:
      type: boolean
  - name: isEqualizeLineHeights
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowAuthor
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowChatTitle
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowTimestamp
    modifiers:
      - public
    return:
      type: boolean
  - name: isUnique
    modifiers:
      - public
    return:
      type: boolean
  - name: isUseOnlyActiveTab
    modifiers:
      - public
    return:
      type: boolean
  - name: pack
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: bb
        type: ByteBufferWriter
  - name: setAllowBBcode
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: allowBBcode
        type: boolean
  - name: setAllowChatIcons
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: allowChatIcons
        type: boolean
  - name: setAllowColors
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: allowColors
        type: boolean
  - name: setAllowFonts
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: allowFonts
        type: boolean
  - name: setAllowImages
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: allowImages
        type: boolean
  - name: setBold
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: bold
        type: boolean
  - name: setEqualizeLineHeights
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: equalizeLineHeights
        type: boolean
  - name: setFont
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: font
        type: UIFont
  - name: setFontColor
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: fontColor
        type: Color
  - name: setFontColor
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: r
        type: float
      - name: g
        type: float
      - name: b
        type: float
      - name: a
        type: float
  - name: setFontSize
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: fontSize
        type: String
  - name: setRange
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: range
        type: float
  - name: setShowAuthor
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: showAuthor
        type: boolean
  - name: setShowChatTitle
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: showChatTitle
        type: boolean
  - name: setShowTimestamp
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: showTimestamp
        type: boolean
  - name: setUnique
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: unique
        type: boolean
  - name: setUseOnlyActiveTab
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: useOnlyActiveTab
        type: boolean
  - name: setZombieAttractionRange
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: zombieAttractionRange
        type: float
