# zombie.chat.ChatSettings
package: zombie.chat
type: class
name: ChatSettings
extends: Object
modifiers:
  - public
fields:
  - name: infinityRange
    modifiers:
      - public
      - static
      - final
    return:
      type: float
constructors:
  - name: ChatSettings
    modifiers:
      - public
  - name: ChatSettings
    modifiers:
      - public
methods:
  - name: getFont
    modifiers:
      - public
    return:
      type: UIFont
  - name: getFontColor
    modifiers:
      - public
    return:
      type: Color
  - name: getFontSize
    modifiers:
      - public
    return:
      type: String
  - name: getRange
    modifiers:
      - public
    return:
      type: float
  - name: getZombieAttractionRange
    modifiers:
      - public
    return:
      type: float
  - name: isAllowBBcode
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowChatIcons
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowColors
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowFonts
    modifiers:
      - public
    return:
      type: boolean
  - name: isAllowImages
    modifiers:
      - public
    return:
      type: boolean
  - name: isBold
    modifiers:
      - public
    return:
      type: boolean
  - name: isEqualizeLineHeights
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowAuthor
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowChatTitle
    modifiers:
      - public
    return:
      type: boolean
  - name: isShowTimestamp
    modifiers:
      - public
    return:
      type: boolean
  - name: isUnique
    modifiers:
      - public
    return:
      type: boolean
  - name: isUseOnlyActiveTab
    modifiers:
      - public
    return:
      type: boolean
  - name: pack
    modifiers:
      - public
    return:
      type: void
  - name: setAllowBBcode
    modifiers:
      - public
    return:
      type: void
  - name: setAllowChatIcons
    modifiers:
      - public
    return:
      type: void
  - name: setAllowColors
    modifiers:
      - public
    return:
      type: void
  - name: setAllowFonts
    modifiers:
      - public
    return:
      type: void
  - name: setAllowImages
    modifiers:
      - public
    return:
      type: void
  - name: setBold
    modifiers:
      - public
    return:
      type: void
  - name: setEqualizeLineHeights
    modifiers:
      - public
    return:
      type: void
  - name: setFont
    modifiers:
      - public
    return:
      type: void
  - name: setFontColor
    modifiers:
      - public
    return:
      type: void
  - name: setFontColor
    modifiers:
      - public
    return:
      type: void
    parameters:
      - name: r
        type: float
      - name: g
        type: " float"
      - name: b
        type: " float"
  - name: setFontSize
    modifiers:
      - public
    return:
      type: void
  - name: setRange
    modifiers:
      - public
    return:
      type: void
  - name: setShowAuthor
    modifiers:
      - public
    return:
      type: void
  - name: setShowChatTitle
    modifiers:
      - public
    return:
      type: void
  - name: setShowTimestamp
    modifiers:
      - public
    return:
      type: void
  - name: setUnique
    modifiers:
      - public
    return:
      type: void
  - name: setUseOnlyActiveTab
    modifiers:
      - public
    return:
      type: void
  - name: setZombieAttractionRange
    modifiers:
      - public
    return:
      type: void
