# zombie.vehicles.EditVehicleState.LuaEnvironment
package: zombie.vehicles
type: class
name: EditVehicleState.LuaEnvironment
extends: Object
modifiers:
  - public
  - static
  - final
fields:
  - name: caller
    modifiers:
      - public
    return:
      type: se.krka.kahlua.integration.LuaCaller
  - name: env
    modifiers:
      - public
    return:
      type: se.krka.kahlua.vm.KahluaTable
  - name: platform
    modifiers:
      - public
    return:
      type: se.krka.kahlua.j2se.J2SEPlatform
  - name: thread
    modifiers:
      - public
    return:
      type: se.krka.kahlua.vm.KahluaThread
constructors:
  - name: LuaEnvironment
    modifiers:
      - public
    parameters:
      - name: platform
        type: se.krka.kahlua.j2se.J2SEPlatform
      - name: converterManager
        type: se.krka.kahlua.converter.KahluaConverterManager
      - name: env
        type: se.krka.kahlua.vm.KahluaTable
