# zombie.config.BooleanConfigOption
package: zombie.config
type: class
name: BooleanConfigOption
extends: ConfigOption
modifiers:
  - public
constructors:
  - name: BooleanConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
methods:
  - name: getDefaultValue
    modifiers:
      - public
    return:
      type: boolean
  - name: getTooltip
    modifiers:
      - public
    return:
      type: String
  - name: getType
    modifiers:
      - public
    return:
      type: String
  - name: getValue
    modifiers:
      - public
    return:
      type: boolean
  - name: getValueAsObject
    modifiers:
      - public
    return:
      type: Object
  - name: getValueAsString
    modifiers:
      - public
    return:
      type: String
  - name: isValidString
    modifiers:
      - public
    return:
      type: boolean
  - name: parse
    modifiers:
      - public
    return:
      type: void
  - name: resetToDefault
    modifiers:
      - public
    return:
      type: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
    return:
      type: void
  - name: setValue
    modifiers:
      - public
    return:
      type: void
  - name: setValueFromObject
    modifiers:
      - public
    return:
      type: void
