# zombie.config.ConfigFile
package: zombie.config
type: class
name: ConfigFile
extends: Object
modifiers:
  - public
  - final
constructors:
  - name: ConfigFile
    modifiers:
      - public
methods:
  - name: getOptions
    modifiers:
      - public
    return:
      type: ArrayList
      generic: ArrayList<ConfigOption>
  - name: getVersion
    modifiers:
      - public
    return:
      type: int
  - name: read
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: fileName
        type: String
  - name: write
    modifiers:
      - public
    return:
      type: boolean
    parameters:
      - name: fileName
        type: String
      - name: version
        type: int
      - name: options
        type: ArrayList
        generic: ArrayList<? extends ConfigOption>
