# zombie.config.ConfigOption
package: zombie.config
type: class
name: ConfigOption
extends: Object
modifiers:
  - public
  - abstract
constructors:
  - name: ConfigOption
    modifiers:
      - public
methods:
  - name: getName
    modifiers:
      - public
    returnType: String
  - name: getTooltip
    modifiers:
      - public
      - abstract
    returnType: String
  - name: getType
    modifiers:
      - public
      - abstract
    returnType: String
  - name: getValueAsLuaString
    modifiers:
      - public
    returnType: String
  - name: getValueAsObject
    modifiers:
      - public
      - abstract
    returnType: Object
  - name: getValueAsString
    modifiers:
      - public
      - abstract
    returnType: String
  - name: isValidString
    modifiers:
      - public
      - abstract
    returnType: boolean
  - name: parse
    modifiers:
      - public
      - abstract
    returnType: void
  - name: resetToDefault
    modifiers:
      - public
      - abstract
    returnType: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
      - abstract
    returnType: void
  - name: setValueFromObject
    modifiers:
      - public
      - abstract
    returnType: void
