# zombie.config.ConfigOption
package: zombie.config
type: class
name: ConfigOption
extends: Object
modifiers:
  - public
  - abstract
constructors:
  - name: ConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
methods:
  - name: getName
    modifiers:
      - public
    return:
      type: String
  - name: getTooltip
    modifiers:
      - public
      - abstract
    return:
      type: String
  - name: getType
    modifiers:
      - public
      - abstract
    return:
      type: String
  - name: getValueAsLuaString
    modifiers:
      - public
    return:
      type: String
  - name: getValueAsObject
    modifiers:
      - public
      - abstract
    return:
      type: Object
  - name: getValueAsString
    modifiers:
      - public
      - abstract
    return:
      type: String
  - name: isValidString
    modifiers:
      - public
      - abstract
    return:
      type: boolean
    parameters:
      - name: s
        type: String
  - name: parse
    modifiers:
      - public
      - abstract
    return:
      type: void
    parameters:
      - name: s
        type: String
  - name: resetToDefault
    modifiers:
      - public
      - abstract
    return:
      type: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
      - abstract
    return:
      type: void
  - name: setValueFromObject
    modifiers:
      - public
      - abstract
    return:
      type: void
    parameters:
      - name: o
        type: Object
