# zombie.config.DoubleConfigOption
package: zombie.config
type: class
name: DoubleConfigOption
extends: ConfigOption
modifiers:
  - public
constructors:
  - name: DoubleConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
      - name: min
        type: " double"
      - name: max
        type: " double"
methods:
  - name: getDefaultValue
    modifiers:
      - public
    returnType: double
  - name: getMax
    modifiers:
      - public
    returnType: double
  - name: getMin
    modifiers:
      - public
    returnType: double
  - name: getTooltip
    modifiers:
      - public
    returnType: String
  - name: getType
    modifiers:
      - public
    returnType: String
  - name: getValue
    modifiers:
      - public
    returnType: double
  - name: getValueAsObject
    modifiers:
      - public
    returnType: Object
  - name: getValueAsString
    modifiers:
      - public
    returnType: String
  - name: isValidString
    modifiers:
      - public
    returnType: boolean
  - name: parse
    modifiers:
      - public
    returnType: void
  - name: resetToDefault
    modifiers:
      - public
    returnType: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
    returnType: void
  - name: setValue
    modifiers:
      - public
    returnType: void
  - name: setValueFromObject
    modifiers:
      - public
    returnType: void
