# zombie.config.EnumConfigOption
package: zombie.config
type: class
name: EnumConfigOption
extends: IntegerConfigOption
modifiers:
  - public
constructors:
  - name: EnumConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
      - name: numValues
        type: " int"
methods:
  - name: getNumValues
    modifiers:
      - public
    return:
      type: int
  - name: getType
    modifiers:
      - public
    return:
      type: String
