# zombie.config.IntegerConfigOption
package: zombie.config
type: class
name: IntegerConfigOption
extends: ConfigOption
modifiers:
  - public
constructors:
  - name: IntegerConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
      - name: min
        type: " int"
      - name: max
        type: " int"
methods:
  - name: getDefaultValue
    modifiers:
      - public
    return:
      type: int
  - name: getMax
    modifiers:
      - public
    return:
      type: double
  - name: getMin
    modifiers:
      - public
    return:
      type: double
  - name: getTooltip
    modifiers:
      - public
    return:
      type: String
  - name: getType
    modifiers:
      - public
    return:
      type: String
  - name: getValue
    modifiers:
      - public
    return:
      type: int
  - name: getValueAsObject
    modifiers:
      - public
    return:
      type: Object
  - name: getValueAsString
    modifiers:
      - public
    return:
      type: String
  - name: isValidString
    modifiers:
      - public
    return:
      type: boolean
  - name: parse
    modifiers:
      - public
    return:
      type: void
  - name: resetToDefault
    modifiers:
      - public
    return:
      type: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
    return:
      type: void
  - name: setValue
    modifiers:
      - public
    return:
      type: void
  - name: setValueFromObject
    modifiers:
      - public
    return:
      type: void
