# zombie.config.StringConfigOption
package: zombie.config
type: class
name: StringConfigOption
extends: ConfigOption
modifiers:
  - public
constructors:
  - name: StringConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
      - name: defaultValue
        type: " String"
methods:
  - name: getDefaultValue
    modifiers:
      - public
    return:
      type: String
  - name: getTooltip
    modifiers:
      - public
    return:
      type: String
  - name: getType
    modifiers:
      - public
    return:
      type: String
  - name: getValue
    modifiers:
      - public
    return:
      type: String
  - name: getValueAsLuaString
    modifiers:
      - public
    return:
      type: String
  - name: getValueAsObject
    modifiers:
      - public
    return:
      type: Object
  - name: getValueAsString
    modifiers:
      - public
    return:
      type: String
  - name: isValidString
    modifiers:
      - public
    return:
      type: boolean
  - name: parse
    modifiers:
      - public
    return:
      type: void
  - name: resetToDefault
    modifiers:
      - public
    return:
      type: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
    return:
      type: void
  - name: setValue
    modifiers:
      - public
    return:
      type: void
  - name: setValueFromObject
    modifiers:
      - public
    return:
      type: void
