# zombie.config.StringConfigOption
package: zombie.config
type: class
name: StringConfigOption
extends: ConfigOption
modifiers:
  - public
constructors:
  - name: StringConfigOption
    modifiers:
      - public
    parameters:
      - name: name
        type: String
      - name: defaultValue
        type: String
      - name: maxLength
        type: int
methods:
  - name: getDefaultValue
    modifiers:
      - public
    returnType: String
  - name: getTooltip
    modifiers:
      - public
    returnType: String
  - name: getType
    modifiers:
      - public
    returnType: String
  - name: getValue
    modifiers:
      - public
    returnType: String
  - name: getValueAsLuaString
    modifiers:
      - public
    returnType: String
  - name: getValueAsObject
    modifiers:
      - public
    returnType: Object
  - name: getValueAsString
    modifiers:
      - public
    returnType: String
  - name: isValidString
    modifiers:
      - public
    returnType: boolean
    parameters:
      - name: s
        type: String
  - name: parse
    modifiers:
      - public
    returnType: void
    parameters:
      - name: s
        type: String
  - name: resetToDefault
    modifiers:
      - public
    returnType: void
  - name: setDefaultToCurrentValue
    modifiers:
      - public
    returnType: void
  - name: setValue
    modifiers:
      - public
    returnType: void
    parameters:
      - name: value
        type: String
  - name: setValueFromObject
    modifiers:
      - public
    returnType: void
    parameters:
      - name: o
        type: Object
